apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: falco
    meta.helm.sh/release-namespace: falco
  creationTimestamp: "2025-03-07T04:06:55Z"
  labels:
    app.kubernetes.io/component: ui
    app.kubernetes.io/instance: falco
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: falcosidekick
    app.kubernetes.io/part-of: falcosidekick
    app.kubernetes.io/version: 2.31.1
    helm.sh/chart: falcosidekick-0.9.11
  name: falco-falcosidekick-ui-redis
  namespace: falco
  resourceVersion: "12817818632"
  uid: 5d7fdc37-0722-48d4-b894-4a9eedffd9e6
spec:
  clusterIP: 172.16.252.117
  clusterIPs:
  - 172.16.252.117
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app.kubernetes.io/component: ui-redis
    app.kubernetes.io/instance: falco
    app.kubernetes.io/name: falcosidekick
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}