apiVersion: apps/v1
kind: Deployment
metadata:
  name: sl-front-dev-blue
  labels:
    app: sl-front-dev
    version: blue
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: sl-front-dev
        version: blue
    spec:
      containers:
        - name: sl-front-dev
          image: ow-tcr.tencentcloudcr.com/ow-tke-tcr/sl-front-dev:0.0.463
          ports:
            - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sl-front-dev-green
  labels:
    app: sl-front-dev
    version: green
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: sl-front-dev
        version: green
    spec:
      containers:
        - name: sl-front-dev
          image: ow-tcr.tencentcloudcr.com/ow-tke-tcr/sl-front-dev:0.0.464
          ports:
            - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: sl-front-dev-service
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: sl-front-dev
    version: blue  # Blue 버전으로 트래픽을 보내기 위해 "blue"로 설정
  type: NodePort
