# values.yaml
image:
  repository: percona/pmm-server
  tag: "3.0.0"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "2000m"
    memory: "2Gi"

storage:
  enabled: true
  accessModes: ["ReadWriteOnce"]
  size: 30Gi
  storageClass: "nfs-client"

ingress:
  enabled: false  # 필요하면 true로 설정