# filebeat-yalues.yaml
filebeatConfig:
  filebeat.yml: |
    filebeat.inputs:
    - type: container
      paths:
        - /var/log/containers/*.log
      symlinks: true
      processors:
        # Kubernetes Metadata Processor
        - add_kubernetes_metadata:
            host: ${NODE_NAME}
            matchers:
              - logs_path:
                  logs_path: "/var/log/containers/"
        
        # Dissect Processor: Logs Parsing
        - dissect:
            tokenizer: "%{timestamp} %{+time} %{log.level} %{service} %{message}"
            field: "message"
            target_prefix: "log"
        
        # Drop events that don't have 'log.level'
        - drop_event:
            when:
              not:
                has_fields: ["log.level"]

    output.logstash:
      hosts: ['logstash-logstash:5044']

    path.data: /var/lib/filebeat/${NODE_NAME}

extraVolumeMounts:
  - name: varlogcontainers
    mountPath: /var/log/containers
    readOnly: true

extraVolumes:
  - name: varlogcontainers
    hostPath:
      path: /var/log/containers

resources:
  requests:
    memory: "500Mi"
    cpu: "500m"
  limits:
    memory: "1Gi"
    cpu: "1000m"